version: "3"
services:
  pythonbot:
    build:
      context: ./PythonBot
    volumes:
      - ./PythonBot:/usr/src/PythonBot
    restart: unless-stopped
    logging:
      options:
        max-size: "200m"
        max-file: "20"

  pythonbot_api:
    build:
      context: ./PythonBot
    volumes:
      - ./PythonBot:/usr/src/PythonBot
    ports:
      - 5000:5000
    entrypoint: python -u run_api.py
    restart: unless-stopped
    logging:
      options:
        max-size: "200m"
        max-file: "20"

  mongodb:
    image: mongo:4.2
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    logging:
      options:
        max-size: "200m"
        max-file: "20"

volumes:
  mongo_data:
