version: "3"
services:
  pythonbot:
    build:
      context: ./PythonBot
    volumes:
      - ./PythonBot:/usr/src/PythonBot
    restart: unless-stopped


  pythonbot_api:
    build:
      context: ./PythonBot
    volumes:
      - ./PythonBot:/usr/src/PythonBot
    ports:
      - 5000:5000
    entrypoint: python -u run_api.py
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=undef"
      - "MONGO_INITDB_ROOT_PASSWORD=undef"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: