---

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master, development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.8

    # Setting up fake secrets
    - name: Setup fake secrets
      run: |
        echo -e "DBAddress = 'mongodb'\nDBName = 'undef'\nDBPassword = 'undef'\nDBPort = 27017\n" >> PythonBot/secret/secrets.py
        echo -e "MONGO_INITDB_ROOT_USERNAME=undef\nMONGO_INITDB_ROOT_PASSWORD=undef" >> .env

    - name: Creating very useful directories
      run: mkdir PythonBot/logs

    - name: Build dockerfile
      run: docker-compose build

    - name: Run unit tests
      run: |
        docker-compose up -d mongodb
        sleep 2
        docker-compose run pythonbot python -m unittest
